name: example
description: Example app for biometric_iot_bridge

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  biometric_iot_bridge:
    path: ../

dev_dependencies:
  flutter_lints: ^3.0.0
